<html>
<head>
    <title>Configure</title>
</head>
<body>
    <div>
        <p>
        BotFather have created the bot for you, now we need token generated by bot father for us to automate your bot. <br>
        Copy and Paste token given by BotFather to below input field:
        </p>
    </div>
    <form onsubmit="loadDoc(); return false;">
        @csrf
        Bot token : <input style="width:30%" type="text" id="token" name="token" placeholder="example: 99853088:AAFfd36hf6btwTjGNF1R_9_gt48tgdhtzRK8"/> <br/><br/>
        Bot Username : <input type="text" id="botuname" name="botuname" value="{{$botuname}}"> <br/><br/>
        Merchant Id : <input type="text" id="userid" name="userid" value="{{$userid}}"> <br/>
        <button>submit</button>
    </form>
    
    <div>
        <pre id="demo">
            Testing    
        </pre>
    </div>

    <script>
        function loadDoc() {

            $botuname = document.getElementById("botuname").value;
            $userid = document.getElementById("userid").value;
            $token = document.getElementById("token").value;

            if (!$botuname || !$userid  || !$token ) {
                document.getElementById("demo").innerHTML = "All field are required";
                return false;
            }

            var data = {
                botuname : $botuname,
                userid : $userid,
                token : $token
            };
            

            const xhttp = new XMLHttpRequest();
            xhttp.onreadystatechange  = function() {
                if(xhttp.readyState == 4) {
                    if (xhttp.status == 200)
                    document.getElementById("demo").innerHTML = xhttp.responseText;
                    else 
                    document.getElementById("demo").innerHTML = xhttp.responseText;
                }
            }
            xhttp.open("POST", "/bottoken");
            xhttp.setRequestHeader("Content-Type", "application/json");
            xhttp.setRequestHeader("Accept", "application/json");
            xhttp.send(JSON.stringify(data));
        }
    </script>
</body>
</html>