<html>
<head>
</head>
<body>
<pre>
BotFather have created the bot for you, now we need token generated by bot father for us to automate your bot...

Copy and Paste token given by BotFather to below input field:
</pre>
Bot token : <input style="width:30%" type="text" placeholder="example: 161053088:AAFfd36hf6btwTjGNF1R_9_gt48tgdhtzRK8"/>
<button>submit</button>
</body>
</html>